Repository SlaybaughLab/BART, pull requests merged in 2018-03, with the labels that each got.

#62 Change coding style to Google Style
  src/aqdata/aq_base.cc
  src/aqdata/aq_base.h
  src/aqdata/lsgc.cc
  src/aqdata/lsgc.h
  src/common/problem_definition.cc
  src/common/problem_definition.h
  src/mesh/mesh_generator.cc
  src/mesh/mesh_generator.h
  tests/aqdata/aq_base_01.cc
  tests/aqdata/aq_base_1d.cc
  tests/aqdata/dummy_test.cc
  tests/aqdata/lsgc_01.cc
  tests/aqdata/lsgc_non_ep.cc
  tests/common/problem_definition_01.cc
  tests/mesh/mesh_generator_01.cc
  tests/mesh/mesh_generator_all_d.cc
  tests/test_utilities.h
Labels: enhancement

#74 Gtests for AQBase and LSGC
  CMakeLists.txt
  src/aqdata/aq_base.cc
  src/aqdata/aq_base.h
  src/aqdata/tests/aq_base_test.cc
  src/aqdata/tests/data/aq_base_1d.gold
  src/aqdata/tests/data/aq_base_1d_ep.gold
  src/aqdata/tests/lsgc_test.cc
  tests/aqdata/CMakeLists.txt
  tests/aqdata/aq_base_01.cc
  tests/aqdata/aq_base_01.output
  tests/aqdata/aq_base_1d.cc
  tests/aqdata/aq_base_1d.output
  tests/aqdata/dummy_test.cc
  tests/aqdata/dummy_test.output
  tests/aqdata/lsgc_01.cc
  tests/aqdata/lsgc_01.output
  tests/aqdata/lsgc_non_ep.cc
  tests/aqdata/lsgc_non_ep.output
Labels: testing

#76 Creating AQ builder.
  src/common/bart_builder.cc
  src/common/bart_builder.h
  src/common/tests/bart_builder_test.cc
  src/common/tests/data/aq_builder_1d.gold
  src/common/tests/data/aq_builder_2d.gold
  src/common/tests/data/aq_builder_3d.gold
Labels: enhancement, testing
